const FIRST_NUMBER = prompt('Enter a number:');
const SECOND_NUMBER = prompt('Enter a number:');
const sum = Number(FIRST_NUMBER) + Number(SECOND_NUMBER);
const substract = Number(FIRST_NUMBER) - Number(SECOND_NUMBER);
const multiply = Number(FIRST_NUMBER) * Number(SECOND_NUMBER);
const divide = Number(FIRST_NUMBER) / Number(SECOND_NUMBER);
alert(`The sum is ${sum}`);
alert(`The substraction result is ${substract}`);
alert(`The multiplication result is ${multiply}`);
alert(`The division is ${divide}`);